version: "3.8"

services:
  dbserver:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - bootapp
  redis-server:
    container_name: redis
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - bootapp
  nginx-server:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    networks:
      - bootapp
  backend:
    container_name: backend
    build: ./boot
    depends_on:
      - dbserver
      - redis-server
    # links:
    #   - redis-server
    environment:
      - spring.datasource.url=jdbc:mysql://dbserver:3306/javascrpittest?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.redis.host=redis-server
      - spring.redis.port=6379
    ports:
      - 4000:4000
    networks:
      - bootapp
  frontend:
    container_name: frontend
    build: ./build
    ports:
      - 3000:3000
networks:
  bootapp:
